version: "3.7"

volumes:
  postgres-data:
    driver: local

networks:
  external:
    name: "delivery-api"

services:
  postgres:
    image: postgres:9.6
    container_name: delivery-db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - external
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    container_name: adminer
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASS}
      - DB_NAME=${DB_NAME}
    ports:
      - "8080:8080"
    networks:
      - external
    depends_on:
      - postgres
